name: Node.js CI

on:
  push:
    branches: [ "master" ]
  

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.11.0]
    env:
      NEXT_WEBSITE_URL: ${{ secrets.NEXT_WEBSITE_URL }}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Change Directory
      run: cd /home/kyanlabs/actions-runner/kyanlabs/new_kyanlabs/new_kyanlabs
    - run: pm2 restart 0
